[workspace]
members = [
    "programs/dregan-nft",
    "programs/dregan-staking"
]
resolver = "2"

[workspace.dependencies]
base64ct = "=1.6.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3