[package]
name = "dregan-staking"
version = "0.1.0"
description = "DREGAN Staking Program for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dregan_staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "=0.28.0"
anchor-spl = "=0.28.0"

[dev-dependencies]
anchor-client = "=0.28.0"