[package]
name = "dregan-staking"
version = "0.1.0"
description = "DREGAN Staking Program for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "=1.17.28"
borsh = "=0.10.3"
thiserror = "=1.0.40"
spl-token = { version = "=4.0.0", features = ["no-entrypoint"] }